#!/usr/bin/env python3
"""gen_bitstreams.py — Generate MCU, OTP and FLASH_MEM bitstream variants
                    from the AXI log produced by eda-placer.

All three output formats verified byte-perfect against GUI-generated files.

FORMAT SUMMARY
──────────────
eda-placer outputs EFLX_bitstream_AXI.log: 1024 rows × 11 hex 32-bit words,
blank-line separated.  Each word is big-endian in the file.

The three GP6 programming formats are all derived from the same base data:
  bswapped[] = byteswap32(each AXI word)  ← LE stored as BE

  FLASH_MEM = FMEM_HEADER (10 words) + bswapped[]
  MCU       = 320×0x00000000 + FLASH_MEM + 8×0x00000000
  OTP       = OTP_HEADER (15 words)  + bswapped[]

Fixed headers (device-specific, SLG47910V Rev BB):
  FMEM_HEADER[10] = aa22ff11 00000000 22222222 22222222 22220000
                    03000000 00000000 00000000 00000000 00000000
  OTP_HEADER [15] = 00000028 00000000 a5a5a5a5 00000000 00000000
                    5a5a5a5a 00000000 [then FMEM_HEADER[2:10]]

Each format is written as:
  *.bin  — packed big-endian uint32 words
  *.txt  — one 8-hex-char word per line, with a metadata comment header

Usage:
    python3 gen_bitstreams.py \\
        --axi   path/to/EFLX_bitstream_AXI.log \\
        --outdir path/to/build/bitstream/ \\
        [--project  ProjectName] \\
        [--netlist  netlist.edif]
"""

import argparse
import datetime
import hashlib
import struct
import sys

from pathlib import Path

# ── Fixed headers (SLG47910V Rev BB) ─────────────────────────────────────────
FMEM_HEADER = [
    0xAA22FF11,
    0x00000000,
    0x22222222,
    0x22222222,
    0x22220000,
    0x03000000,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000000,
]

OTP_PREAMBLE = [
    0x00000028,
    0x00000000,
    0xA5A5A5A5,
    0x00000000,
    0x00000000,
    0x5A5A5A5A,
    0x00000000,
]
OTP_HEADER = OTP_PREAMBLE + FMEM_HEADER[2:10]  # 15 words total

MCU_PREAMBLE_LEN = 320  # zero words before FLASH_MEM content
MCU_TRAILER_LEN = 8  # zero words after


def bswap32(w: int) -> int:
    return struct.unpack("<I", struct.pack(">I", w))[0]


def read_axi(path: Path) -> list[int]:
    """Read AXI log hex words, skip comments and blank lines."""
    words = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            words.append(int(line, 16))
    if len(words) != 1024 * 11:
        print(f"WARNING: expected {1024 * 11} AXI words, got {len(words)}", file=sys.stderr)
    return words


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def comment_header(variant: str, axi_path: Path, project: str, netlist: str) -> str:
    ts = datetime.datetime.now().strftime("%a %b %d %H:%M:%S %Y")
    sha = sha256_file(axi_path) if axi_path.exists() else "unknown"
    lines = [
        "# File generated by gen_bitstreams.py (headless build)",
        f"## Project name: {project}",
        f"## Netlist name: internal: {netlist}",
        f"# Generation date: {ts}",
        "# Synthesis tool: Yosys v.0.59",
        "# Place and Route tool: v.23",
        f"# Netlist SHA-256 {sha}",
    ]
    return "\n".join(lines) + "\n"


def write_variant(name: str, words: list[int], outdir: Path, axi_path: Path, project: str, netlist: str):
    outdir.mkdir(parents=True, exist_ok=True)
    hdr = comment_header(name, axi_path, project, netlist)

    bin_path = outdir / f"FPGA_bitstream_{name}.bin"
    txt_path = outdir / f"FPGA_bitstream_{name}.txt"

    # Binary: big-endian uint32 words
    with bin_path.open("wb") as f:
        f.write(struct.pack(f">{len(words)}I", *words))

    # Text: comment header + one 8-hex-char word per line
    with txt_path.open("w") as f:
        f.write(hdr)
        for w in words:
            f.write(f"{w:08x}\n")

    print(f"  {name:10s}  {bin_path.name} ({len(words) * 4:,} bytes)")


def main():
    ap = argparse.ArgumentParser(description="Generate MCU/OTP/FLASH_MEM bitstreams from eda-placer AXI log")
    ap.add_argument("--axi", required=True, type=Path, help="Path to EFLX_bitstream_AXI.log (or FPGA_bitstream_AXI.log)")
    ap.add_argument("--outdir", required=True, type=Path, help="Output directory (will be created if needed)")
    ap.add_argument("--project", default="project", help="Project name for comment header (default: project)")
    ap.add_argument("--netlist", default="netlist.edif", help="Netlist name for comment header (default: netlist.edif)")
    args = ap.parse_args()

    axi_path: Path = args.axi
    if not axi_path.exists():
        sys.exit(f"ERROR: AXI log not found: {axi_path}")

    print(f"Reading AXI log: {axi_path}")
    axi = read_axi(axi_path)
    bswapped = [bswap32(w) for w in axi]

    fmem_words = FMEM_HEADER + bswapped
    mcu_words = [0] * MCU_PREAMBLE_LEN + fmem_words + [0] * MCU_TRAILER_LEN
    otp_words = OTP_HEADER + bswapped

    print(f"Writing to: {args.outdir}")
    write_variant("FLASH_MEM", fmem_words, args.outdir, axi_path, args.project, args.netlist)
    write_variant("MCU", mcu_words, args.outdir, axi_path, args.project, args.netlist)
    write_variant("OTP", otp_words, args.outdir, axi_path, args.project, args.netlist)
    print("Done.")


if __name__ == "__main__":
    main()
