#!/usr/bin/env python3
"""shrike-gen — Project scaffolding for SLG47910V (ForgeFPGA) & Shrike Lite

Creates a complete, ready-to-build project directory from scratch.

USAGE
─────
    python3 shrike_gen/shrike-gen.py <ProjectName> [options]
    ./shrike-gen <ProjectName> [options]           # after: make init

    Options:
      --top NAME      Top-level Verilog module name (default: same as ProjectName)
      --dir PATH      Parent directory for the new project (default: current directory)
      --force         Overwrite an existing project directory

CREATED STRUCTURE
─────────────────
    ProjectName/
    ├── Makefile          ← role-aware build file (project mode)
    ├── shrike.mk         ← PROJECT / TOP identity (included by Makefile)
    ├── ProjectName.ffpga ← GUI project file (regenerated by make update)
    ├── io_map.pcf        ← IO constraints — edit this to assign signals to pins
    ├── ffpga/
    │   ├── src/
    │   │   └── main.v    ← top-level Verilog — edit this
    │   └── build/
    │       ├── floorplanspec.fp   ← fixed device file (do not edit)
    │       └── io_spec_in.txt     ← regenerated by make update (do not edit)
    └── shrike_gen/       ← generator scripts (do not edit)

WORKFLOW
────────
    make project MyProject          # 1. create skeleton (workspace root)
    $EDITOR MyProject/ffpga/src/main.v    # 2. write your Verilog
    $EDITOR MyProject/io_map.pcf          # 3. assign signals to pins
    cd MyProject && make                  # 4. build

    # Subsequent builds (inside project):
    make          → make update + make build
    make update   → regenerate .ffpga and io_spec_in.txt only
    make build    → lint → synth → pnr → collect bitstreams
    make clean    → remove all build artefacts (keeps source + constraints)
"""

import argparse
import os
import re
import shutil
import sys

from pathlib import Path

# ── Resource paths ─────────────────────────────────────────────────────────────
# When invoked via the ./shrike-gen symlink or directly, __file__ resolves to
# this script inside shrike_gen/.  Everything is relative to that.
_HERE = Path(__file__).resolve().parent  # .../shrike_gen/
_WORKSPACE = _HERE.parent  # workspace root (contains Makefile)
_TEMPLATES_DIR = _HERE / "templates"

_REQUIRED_TOOLS = [
    "gen_io_spec.py",
    "gen_ffpga.py",
    "gen_fpga_data.py",
    "gen_bitstreams.py",
]


# ── Sanity checks ──────────────────────────────────────────────────────────────


def _check_tools():
    """Verify that all generator scripts are present alongside shrike-gen.py."""
    missing = [t for t in _REQUIRED_TOOLS if not (_HERE / t).exists()]
    if missing:
        sys.exit(f"ERROR: generator scripts not found in {_HERE}/:\n" + "".join(f"  {t}\n" for t in missing) + "\nAll gen_*.py files must live in the same directory as shrike-gen.py.")

    workspace_mk = _WORKSPACE / "Makefile"
    if not workspace_mk.exists():
        sys.exit(f"ERROR: Makefile not found at {workspace_mk}\nThe Makefile must live in the directory above shrike_gen/.")

    templates_missing = []
    for tmpl in ("io_map.pcf", "main.v"):
        if not (_TEMPLATES_DIR / tmpl).exists():
            templates_missing.append(tmpl)
    if templates_missing:
        sys.exit(f"ERROR: template files not found in {_TEMPLATES_DIR}/:\n" + "".join(f"  {t}\n" for t in templates_missing))


# ── Template rendering ─────────────────────────────────────────────────────────


def _render(template_name: str, **subs) -> str:
    """Read shrike_gen/templates/<template_name> and substitute {{KEY}} placeholders.
    """
    text = (_TEMPLATES_DIR / template_name).read_text()
    for key, val in subs.items():
        text = text.replace("{{" + key + "}}", val)
    return text


# ── Project creation ───────────────────────────────────────────────────────────


def create_project(name: str, top: str, parent: Path, force: bool):
    proj_dir = parent / name

    if proj_dir.exists():
        if force:
            shutil.rmtree(proj_dir)
            print(f"Removed existing {proj_dir}")
        else:
            sys.exit(f"ERROR: {proj_dir} already exists.  Use --force to overwrite.")

    # ── Directory tree ────────────────────────────────────────────────────────
    for d in [
        proj_dir / "ffpga" / "src",
        proj_dir / "ffpga" / "build" / "bitstream",
        proj_dir / "ffpga" / "build" / "ta_message",
    ]:
        d.mkdir(parents=True)

    # ── Copy workspace Makefile into project root ─────────────────────────────
    shutil.copy(_WORKSPACE / "Makefile", proj_dir / "Makefile")

    # ── Copy shrike_gen/ into project (scripts + templates) ───────────────────
    shutil.copytree(_HERE, proj_dir / "shrike_gen")

    # ── shrike.mk — project identity consumed by the role-aware Makefile ──────
    (proj_dir / "shrike.mk").write_text(f"# Auto-generated by shrike-gen — do not edit manually\nPROJECT := {name}\nTOP     := {top}\n")

    # ── floorplanspec.fp (fixed 6-byte device descriptor) ────────────────────
    (proj_dir / "ffpga" / "build" / "floorplanspec.fp").write_bytes(b"1K\n\nM\n")

    # ── io_map.pcf from template ──────────────────────────────────────────────
    (proj_dir / "io_map.pcf").write_text(_render("io_map.pcf", PROJECT=name))

    # ── ffpga/src/main.v from template ────────────────────────────────────────
    (proj_dir / "ffpga" / "src" / "main.v").write_text(_render("main.v", TOP=top))

    # ── Generate initial .ffpga and io_spec_in.txt ────────────────────────────
    # Load gen_io_spec and gen_ffpga from _HERE (the source, not the copy).
    import importlib.util as _ilu

    def _load(script: Path, module_name: str):
        spec = _ilu.spec_from_file_location(module_name, script)
        mod = _ilu.module_from_spec(spec)  # type: ignore[arg-type]
        spec.loader.exec_module(mod)  # type: ignore[union-attr]
        return mod

    _gen_io_spec = _load(_HERE / "gen_io_spec.py", "gen_io_spec")
    _gen_ffpga = _load(_HERE / "gen_ffpga.py", "gen_ffpga")

    # Allow gen_ffpga to use the already-loaded gen_io_spec
    _gen_ffpga._gen_io_spec = _gen_io_spec
    _gen_ffpga._have_gen_io_spec = True

    import datetime

    ffpga_xml = _gen_ffpga.build_ffpga(
        project=name,
        sources=["main.v"],
        pcf=proj_dir / "io_map.pcf",
        max_cpu=os.cpu_count() or 1,
        date=datetime.date.today(),
    )
    (proj_dir / f"{name}.ffpga").write_text(ffpga_xml)

    assignments = _gen_io_spec.parse_pcf(proj_dir / "io_map.pcf")
    iomap = _gen_io_spec.resolve(assignments)
    iospec_txt = _gen_io_spec.gen_iospec_txt(iomap)
    (proj_dir / "ffpga" / "build" / "io_spec_in.txt").write_text(iospec_txt)

    # ── Summary ───────────────────────────────────────────────────────────────
    rel = proj_dir.relative_to(parent) if proj_dir.is_relative_to(parent) else proj_dir
    print(f"\n✓  Created project: {proj_dir}/")
    print("\n   Structure:")
    print(f"     {name}/Makefile          ← role-aware build file")
    print(f"     {name}/shrike.mk         ← PROJECT={name} TOP={top}")
    print(f"     {name}/{name}.ffpga")
    print(f"     {name}/io_map.pcf        ← pin constraints (edit this)")
    print(f"     {name}/ffpga/src/main.v  ← Verilog source  (edit this)")
    print(f"     {name}/ffpga/build/")
    print(f"     {name}/shrike_gen/")
    print()
    print("   Workflow:")
    print(f"     $EDITOR {name}/ffpga/src/main.v")
    print(f"     $EDITOR {name}/io_map.pcf")
    print(f"     cd {name} && make")
    print()


# ── Entry point ────────────────────────────────────────────────────────────────


def main():
    ap = argparse.ArgumentParser(description="Create a new SLG47910V / Shrike Lite FPGA project skeleton", formatter_class=argparse.RawDescriptionHelpFormatter, epilog=__doc__)
    ap.add_argument("name", help="Project name (also used as directory name)")
    ap.add_argument("--top", default=None, help="Top-level Verilog module name (default: same as project name)")
    ap.add_argument("--dir", type=Path, default=Path("."), help="Parent directory for the new project (default: current directory)")
    ap.add_argument("--force", action="store_true", help="Overwrite an existing project directory")
    args = ap.parse_args()

    if not re.match(r"^[A-Za-z][A-Za-z0-9_-]*$", args.name):
        sys.exit(f"ERROR: project name must start with a letter and contain only letters, digits, underscores, or hyphens: {args.name!r}")

    top = args.top or args.name
    _check_tools()
    create_project(name=args.name, top=top, parent=args.dir.resolve(), force=args.force)


if __name__ == "__main__":
    main()
